package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

type makeTarget struct {
	Name string
	Help string
}

func main() {
	os.Exit(run(os.Args[1:]))
}

func run(args []string) int {
	flags := flag.NewFlagSet("docsgen", flag.ContinueOnError)
	outputPath := flags.String("output", "docs/reference.md", "generated reference documentation path")
	check := flags.Bool("check", false, "fail if generated documentation differs")
	if err := flags.Parse(args); err != nil {
		return 2
	}

	content, err := generate()
	if err != nil {
		fmt.Fprintf(os.Stderr, "generate docs: %v\n", err)
		return 1
	}

	if *check {
		current, err := os.ReadFile(*outputPath)
		if err != nil {
			fmt.Fprintf(os.Stderr, "read %s: %v\n", *outputPath, err)
			return 1
		}
		if !bytes.Equal(current, content) {
			fmt.Fprintf(os.Stderr, "%s is out of date; run `make docs-generate`\n", *outputPath)
			return 1
		}
		return 0
	}

	if err := os.MkdirAll(filepath.Dir(*outputPath), 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "create docs dir: %v\n", err)
		return 1
	}
	if err := os.WriteFile(*outputPath, content, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write %s: %v\n", *outputPath, err)
		return 1
	}
	return 0
}

func generate() ([]byte, error) {
	var b strings.Builder
	b.WriteString("# Generated Reference\n\n")
	b.WriteString("Generated by `make docs-generate`. Do not edit by hand.\n\n")
	b.WriteString("## Root Make Targets\n\n")
	writeTargets(&b, makeTargets("Makefile", ""))
	b.WriteString("## Scaffold Make Targets\n\n")
	writeTargets(&b, makeTargets("scaffold/Makefile", "scaffold-"))
	b.WriteString("## Scaffold Managed Files\n\n")
	writeList(&b, scaffoldFiles("default_files"))
	b.WriteString("## Scaffold Obsolete Files\n\n")
	writeList(&b, scaffoldFiles("obsolete_files"))
	b.WriteString("## Demo Scaffold Metadata\n\n")
	writeMetadata(&b)
	b.WriteString("## Public API Surfaces\n\n")
	if err := writePublicAPI(&b); err != nil {
		return nil, err
	}
	return []byte(strings.TrimRight(b.String(), "\n") + "\n"), nil
}

func makeTargets(path, prefix string) []makeTarget {
	data := mustRead(path)
	re := regexp.MustCompile(`(?m)^([A-Za-z0-9_-]+):.*?## (.+)$`)
	matches := re.FindAllStringSubmatch(string(data), -1)
	targets := make([]makeTarget, 0, len(matches))
	for _, match := range matches {
		targets = append(targets, makeTarget{Name: prefix + match[1], Help: match[2]})
	}
	sort.Slice(targets, func(i, j int) bool { return targets[i].Name < targets[j].Name })
	return targets
}

func writeTargets(b *strings.Builder, targets []makeTarget) {
	for _, target := range targets {
		fmt.Fprintf(b, "- `%s`: %s\n", target.Name, target.Help)
	}
	b.WriteString("\n")
}

func scaffoldFiles(variable string) []string {
	data := mustRead("scaffold/scripts/scaffold-drift.sh")
	re := regexp.MustCompile(`(?ms)^` + regexp.QuoteMeta(variable) + `=\(\n(.*?)\n\)`)
	match := re.FindSubmatch(data)
	if match == nil {
		fatalf("cannot find %s in scaffold/scripts/scaffold-drift.sh", variable)
	}
	lineRe := regexp.MustCompile(`"([^"]+)"`)
	matches := lineRe.FindAllStringSubmatch(string(match[1]), -1)
	files := make([]string, 0, len(matches))
	for _, match := range matches {
		files = append(files, match[1])
	}
	sort.Strings(files)
	return files
}

func writeList(b *strings.Builder, values []string) {
	for _, value := range values {
		fmt.Fprintf(b, "- `%s`\n", value)
	}
	b.WriteString("\n")
}

func writeMetadata(b *strings.Builder) {
	vars := makeVariables("scaffold/Makefile")
	values := map[string]string{
		"target":       "<temporary directory>",
		"project-name": makeVariable(vars, "CHECK_PROJECT_NAME"),
		"module":       makeVariable(vars, "CHECK_GO_MODULE"),
		"description":  makeVariable(vars, "CHECK_PROJECT_DESC"),
		"feature-name": makeVariable(vars, "CHECK_FEATURE_NAME"),
		"namespace":    makeVariable(vars, "CHECK_METRIC_NAMESPACE"),
		"port":         makeVariable(vars, "CHECK_DEFAULT_PORT"),
		"config-file":  makeVariable(vars, "CHECK_FEATURE_CONFIG_FILE"),
		"framework":    frameworkVersion(),
	}
	keys := []string{"target", "project-name", "module", "description", "feature-name", "namespace", "port", "config-file", "framework"}
	b.WriteString("```text\n")
	b.WriteString("Scaffold metadata:\n")
	for _, key := range keys {
		fmt.Fprintf(b, "  %-13s %s\n", key+":", values[key])
	}
	b.WriteString("```\n\n")
}

func makeVariables(path string) map[string]string {
	data := mustRead(path)
	re := regexp.MustCompile(`(?m)^([A-Z0-9_]+) \?= (.*)$`)
	matches := re.FindAllStringSubmatch(string(data), -1)
	vars := make(map[string]string, len(matches))
	for _, match := range matches {
		vars[match[1]] = strings.TrimSpace(match[2])
	}
	return vars
}

func makeVariable(vars map[string]string, name string) string {
	value, ok := vars[name]
	if !ok {
		fatalf("cannot find %s in Makefile variables", name)
	}
	return expandMakeVariables(value, vars)
}

func expandMakeVariables(value string, vars map[string]string) string {
	re := regexp.MustCompile(`\$\(([A-Z0-9_]+)\)`)
	for {
		changed := false
		value = re.ReplaceAllStringFunc(value, func(match string) string {
			name := strings.TrimSuffix(strings.TrimPrefix(match, "$("), ")")
			replacement, ok := vars[name]
			if !ok {
				return match
			}
			changed = true
			return replacement
		})
		if !changed {
			return value
		}
	}
}

func frameworkVersion() string {
	data := mustRead("scaffold/template/go.mod")
	re := regexp.MustCompile(`(?m)^\s*github\.com/zxzharmlesszxz/prometheus-exporter-framework\s+(v\S+)`)
	match := re.FindSubmatch(data)
	if match == nil {
		fatalf("cannot find framework version in scaffold/template/go.mod")
	}
	version := string(match[1])
	return version + " (scaffold: " + version + ")"
}

func writePublicAPI(b *strings.Builder) error {
	var paths []string
	err := filepath.WalkDir("exporter", func(path string, entry os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.IsDir() {
			return nil
		}
		if filepath.ToSlash(path) == "exporter/testdata/public_api.txt" || strings.HasSuffix(filepath.ToSlash(path), "/testdata/public_api.txt") {
			paths = append(paths, filepath.ToSlash(path))
		}
		return nil
	})
	if err != nil {
		return err
	}
	sort.Strings(paths)

	seen := make(map[string]bool, len(paths))
	for _, path := range paths {
		if seen[path] {
			continue
		}
		seen[path] = true
		data := mustRead(path)
		fmt.Fprintf(b, "### `%s`\n\n", path)
		b.WriteString("```text\n")
		b.Write(data)
		if len(data) == 0 || data[len(data)-1] != '\n' {
			b.WriteByte('\n')
		}
		b.WriteString("```\n\n")
	}
	return nil
}

func mustRead(path string) []byte {
	data, err := os.ReadFile(path)
	if err != nil {
		fatalf("read %s: %v", path, err)
	}
	return data
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}
