---

name: CI

on:
  push:
    branches:
      - "**"
    tags:
      - "**"
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  packages: write

jobs:
  ci:
    uses: zxzharmlesszxz/prometheus-exporter-framework/.github/workflows/exporter-ci.yml@__FRAMEWORK_VERSION__
    with:
      project-name: __PROJECT_NAME__
      go-version: "1.27.0"
      docker-platforms: "linux/amd64,linux/arm64"
    secrets: inherit
