# Overridable defaults. Use ignored Makefile.local for persistent local changes.
GO ?= go
GOFMT ?= gofmt
DOCKER ?= docker
STATICCHECK_VERSION ?= v0.8.1
STATICCHECK ?= $(GO) run honnef.co/go/tools/cmd/staticcheck@$(STATICCHECK_VERSION)
STATICCHECK_GOFLAGS ?= -buildvcs=false
GOVULNCHECK_VERSION ?= v1.7.0
GOVULNCHECK ?= $(GO) run golang.org/x/vuln/cmd/govulncheck@$(GOVULNCHECK_VERSION)
GOLANGCI_LINT_VERSION ?= v2.13.1
GOLANGCI_LINT ?= $(GO) run github.com/golangci/golangci-lint/v2/cmd/golangci-lint@$(GOLANGCI_LINT_VERSION)
COVERAGE_THRESHOLD ?= 85.0
BUILD_OUTPUT ?= $(DIST_DIR)/$(PROJECT_NAME)
CGO_ENABLED ?= 0
VERSION ?= $(shell git describe --tags --always --dirty 2>/dev/null || echo dev)
BRANCH ?= $(shell git rev-parse --abbrev-ref HEAD 2>/dev/null || echo dev)
REVISION ?= $(shell git rev-parse --short HEAD 2>/dev/null || echo dev)
BUILD_USER ?= $(shell whoami 2>/dev/null || echo unknown)
BUILD_DATE ?= $(shell date -u +%Y-%m-%dT%H:%M:%SZ)
PLATFORMS ?= linux/amd64 linux/arm64 darwin/amd64 darwin/arm64
IMAGE_TAG ?= $(VERSION)
DOCKER_IMAGE ?= $(DOCKER_PROJECT_NAME):$(IMAGE_TAG)
DOCKER_HTTP_IMAGE ?= busybox:1.38.0
DOCKER_SMOKE_EXPECTED_VERSION ?= $(VERSION)
DOCKER_SMOKE_EXPECTED_BRANCH ?= $(BRANCH)
DOCKER_SMOKE_EXPECTED_REVISION ?= $(REVISION)
DOCKER_PLATFORMS ?= linux/amd64,linux/arm64
DOCKER_COMPOSE ?= $(DOCKER) compose
COMPOSE_ARGS ?= up --build
COMPOSE_PROJECT_NAME ?= $(PROJECT_NAME)
COMPOSE_EXPORTER_HOST_PORT ?= $(patsubst :%,%,$(DEFAULT_PORT))
PROMETHEUS_IMAGE ?= prom/prometheus:v3.14.0
GRAFANA_IMAGE ?= grafana/grafana:13.2
GRAFANA_ADMIN_USER ?= admin
GRAFANA_ADMIN_PASSWORD ?= admin
SMOKE_DOCKER_IMAGE ?= $(DOCKER_PROJECT_NAME):smoke
SMOKE_VERSION ?= v9.8.7
SMOKE_BRANCH ?= smoke-branch
SMOKE_REVISION ?= abc123def
SMOKE_BUILD_USER ?= smoke-test
SMOKE_BUILD_DATE ?= 2026-05-17T00:00:00Z
SMOKE_BINARY ?= $(DIST_DIR)/$(PROJECT_NAME)
